// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRole int32

const (
	UserRole_ROLE_SUPER_ADMIN UserRole = 0
	UserRole_ROLE_ADMIN       UserRole = 1
	UserRole_ROLE_GURU        UserRole = 2
	UserRole_ROLE_ORANG_TUA   UserRole = 3
)

var UserRole_name = map[int32]string{
	0: "ROLE_SUPER_ADMIN",
	1: "ROLE_ADMIN",
	2: "ROLE_GURU",
	3: "ROLE_ORANG_TUA",
}

var UserRole_value = map[string]int32{
	"ROLE_SUPER_ADMIN": 0,
	"ROLE_ADMIN":       1,
	"ROLE_GURU":        2,
	"ROLE_ORANG_TUA":   3,
}

func (x UserRole) String() string {
	return proto.EnumName(UserRole_name, int32(x))
}

func (UserRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SekolahId            string   `protobuf:"bytes,3,opt,name=sekolah_id,json=sekolahId,proto3" json:"sekolah_id,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	UserRole             UserRole `protobuf:"varint,7,opt,name=user_role,json=userRole,proto3,enum=auth.UserRole" json:"user_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetSekolahId() string {
	if m != nil {
		return m.SekolahId
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetUserRole() UserRole {
	if m != nil {
		return m.UserRole
	}
	return UserRole_ROLE_SUPER_ADMIN
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Token                *Token   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("auth.UserRole", UserRole_name, UserRole_value)
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*Response)(nil), "auth.Response")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Error)(nil), "auth.Error")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xb6, 0x6c, 0xc9, 0x91, 0xc6, 0x58, 0x98, 0xc1, 0x07, 0x11, 0x68, 0x51, 0x14, 0x28, 0x69,
	0x03, 0x39, 0xb8, 0xe7, 0x1e, 0x44, 0x63, 0x4c, 0xa0, 0x4d, 0xca, 0x3a, 0x2a, 0xbd, 0x09, 0xd5,
	0x1a, 0xb0, 0x88, 0xe2, 0x75, 0x77, 0x57, 0xe9, 0x8b, 0xf4, 0x79, 0xfa, 0x66, 0x85, 0xb2, 0x23,
	0xb9, 0x55, 0x43, 0x21, 0x39, 0x79, 0xbe, 0x9f, 0xdd, 0x9d, 0x99, 0xcf, 0x02, 0x28, 0x1a, 0xb3,
	0xbd, 0xd8, 0x2b, 0x69, 0x24, 0xba, 0xb6, 0x4e, 0x7e, 0x3a, 0xe0, 0x66, 0x9a, 0x14, 0x86, 0x30,
	0xac, 0xca, 0xc8, 0x89, 0x9d, 0xb3, 0x40, 0x0c, 0xab, 0x12, 0x11, 0xdc, 0x5d, 0x71, 0x4f, 0xd1,
	0x90, 0x19, 0xae, 0xf1, 0x05, 0x80, 0xa6, 0x3b, 0x59, 0x17, 0xdb, 0xbc, 0x2a, 0xa3, 0x11, 0x2b,
	0x41, 0xc7, 0x5c, 0x95, 0x38, 0x07, 0x8f, 0xee, 0x8b, 0xaa, 0x8e, 0x5c, 0x56, 0x5a, 0x80, 0xc7,
	0xe0, 0xef, 0x0b, 0xad, 0xbf, 0x4b, 0x55, 0x46, 0x1e, 0x0b, 0x7f, 0xb0, 0x3d, 0x61, 0xe4, 0x1d,
	0xed, 0xa2, 0x71, 0x7b, 0x82, 0x01, 0x9e, 0x43, 0xd0, 0x68, 0x52, 0xb9, 0x92, 0x35, 0x45, 0x47,
	0xb1, 0x73, 0x16, 0x2e, 0xc2, 0x0b, 0xee, 0xdc, 0x76, 0x2a, 0x64, 0x4d, 0xc2, 0x6f, 0xba, 0x2a,
	0x09, 0xe0, 0x48, 0xd0, 0xb7, 0x86, 0xb4, 0x49, 0x7e, 0x38, 0xe0, 0x0b, 0xd2, 0x7b, 0xb9, 0xd3,
	0x84, 0x2f, 0xc1, 0xb5, 0x1e, 0x9e, 0x68, 0xb2, 0x80, 0xde, 0x79, 0xe6, 0x31, 0x06, 0xcf, 0xfe,
	0xea, 0x68, 0x18, 0x8f, 0x1e, 0x19, 0x5a, 0x01, 0x4f, 0x61, 0x4c, 0x4a, 0x49, 0xa5, 0xa3, 0x11,
	0x5b, 0x26, 0xad, 0x65, 0x69, 0x39, 0xd1, 0x49, 0x78, 0x72, 0x98, 0xc0, 0xe5, 0x77, 0x3a, 0xcf,
	0xad, 0xa5, 0xba, 0x71, 0x92, 0x2f, 0xe0, 0x31, 0xfe, 0x3b, 0xad, 0xd3, 0x9f, 0x76, 0x0e, 0xde,
	0x43, 0x51, 0x57, 0x25, 0x6f, 0xda, 0x17, 0x2d, 0x78, 0xd6, 0xe3, 0xc9, 0x3b, 0xf0, 0x98, 0xb0,
	0x61, 0x6d, 0x64, 0x49, 0x7c, 0xb1, 0x27, 0xb8, 0xc6, 0x18, 0x26, 0x25, 0xe9, 0x8d, 0xaa, 0xf6,
	0xa6, 0x92, 0xbb, 0x2e, 0xc7, 0x3e, 0xf5, 0x66, 0x0d, 0xfe, 0x61, 0xa1, 0x38, 0x87, 0x99, 0xb8,
	0xf9, 0xb0, 0xcc, 0xd7, 0xd9, 0xa7, 0xa5, 0xc8, 0xd3, 0xcb, 0x8f, 0x57, 0xd7, 0xb3, 0x01, 0x86,
	0x00, 0xcc, 0xb6, 0xd8, 0xc1, 0x29, 0x04, 0x8c, 0x57, 0x99, 0xc8, 0x66, 0x43, 0x44, 0x08, 0x19,
	0xde, 0x88, 0xf4, 0x7a, 0x95, 0xdf, 0x66, 0xe9, 0x6c, 0xb4, 0xf8, 0xe5, 0xc0, 0x24, 0x6d, 0xcc,
	0x76, 0x4d, 0xea, 0xa1, 0xda, 0x10, 0xbe, 0x82, 0xf1, 0x7b, 0x45, 0x85, 0x21, 0xec, 0xad, 0xf8,
	0xb8, 0xcb, 0xf3, 0x90, 0x56, 0x32, 0xb0, 0xbe, 0x4b, 0xaa, 0xe9, 0x49, 0xdf, 0x29, 0x8c, 0x56,
	0x64, 0x9e, 0x30, 0xbd, 0x86, 0xf1, 0x8a, 0x4c, 0x5a, 0xd7, 0x38, 0x3d, 0x68, 0xfc, 0x17, 0xf9,
	0x8f, 0xf5, 0x04, 0x5c, 0xdb, 0xee, 0x3f, 0x17, 0xf6, 0x53, 0x4c, 0x06, 0x78, 0x0e, 0xd3, 0xcf,
	0x36, 0x94, 0xc2, 0x50, 0x1b, 0x64, 0x5f, 0x7f, 0x64, 0xfe, 0x3a, 0xe6, 0xaf, 0xeb, 0xed, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xd1, 0xf4, 0x9a, 0x6b, 0x03, 0x00, 0x00,
}
